# Group Movies
## Movies [/movie/{id}]

### Get a single movie. [GET]
Return information on a specific movie.

Donec id elit non mi porta gravida at eget metus. Cras mattis consectetur purus sit amet fermentum. Lorem
ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Duis
mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Etiam porta
sem malesuada magna mollis euismod.

```
[
  {"id": "fizzbuzz"}
]
```

+ Parameters
    - `id` (number, required) - Movie ID
+ Response 200 (application/json)
    + Attributes (Movie)
+ Response 304 (application/json)
+ Response 404 (application/json)
    + Attributes (Error)

## Movies [/movies/{id}]

### Delete a movie. [DELETE]
Delete a movie.

This action requires a bearer token with the `delete` scope.

+ Parameters
    - `id` (number, required) - Movie ID
+ Response 204 (application/json)
+ Response 404 (application/json)
    + Attributes (Error)

### Get a single movie. [GET]
Return information on a specific movie.

Donec id elit non mi porta gravida at eget metus. Cras mattis consectetur purus sit amet fermentum. Lorem
ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Duis
mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Etiam porta
sem malesuada magna mollis euismod.

```
[
  {"id": "fizzbuzz"}
]
```

+ Parameters
    - `id` (number, required) - Movie ID
+ Response 200 (application/json)
    + Attributes (Movie)
+ Response 304 (application/json)
+ Response 404 (application/json)
    + Attributes (Error)

### Update a movie. [PATCH]
Update a movies data.

This action requires a bearer token with the `edit` scope.

+ Parameters
    - `id` (number, required) - Movie ID
+ Request
    + Attributes
        - `cast` (array) - Array of cast members.
             - (object)
                - `name`: `Natasha Hovey` (string) - Cast member name.
                - `role`: `Cheryl` (string) - Cast member role.
        - `content_rating`: `NR` (enum[string]) - MPAA rating
            + Members
                + `G` - Rated G
                + `NC-17` - Rated NC-17
                + `NR` - Not rated
                + `PG` - Rated PG
                + `PG-13` - Rated PG-13
                + `R` - Rated R
                + `UR` - Unrated
                + `X` - Rated X
        - `description` (string, required) - Description, or tagline, for the movie.
        - `director`: `Lamberto Bava` (string) - Name of the director.
        - `genres` (array[string]) - Array of movie genres.
        - `imdb`: `https://www.imdb.com/title/tt0089013/` (string) - IMDB URL
        - `is_kid_friendly` (boolean) - Is this movie kid friendly?
        - `name`: `Demons` (string, required) - Name of the movie.
        - `rotten_tomatoes_score`: `56` (number) - Rotten Tomatoes score
        - `runtime`: `1hr 20min` (string) - Movie runtime, in `HHhr MMmin` format.
        - `trailer`: `https://www.youtube.com/watch?v=_cNjTdFHL8E` (string, nullable) - Trailer URL
+ Response 200 (application/json)
    + Attributes (Movie)
+ Response 400 (application/json)
    There are two ways that this status code can be encountered:
         * If there is a problem with the request.
         * If the IMDB URL could not be validated.
    + Attributes (Error)
+ Response 404 (application/json)
    + Attributes (Error)

## Movies [/movies]

### Get movies. [GET]
Returns all movies for a specific location.

+ Request
    + Attributes
        - `location` (string, required) - Location you want movies for.
        - `page` (number) - Page of results to pull.
+ Response 200 (application/json)
    + Attributes (array[Movie])
+ Response 400 (application/json)
    + Attributes (Error)

### Create a movie. [POST]
Create a new movie.

This action requires a bearer token with the `create` scope.

+ Request
    + Attributes
        - `cast` (array) - Array of cast members.
             - (object)
                - `name`: `Natasha Hovey` (string) - Cast member name.
                - `role`: `Cheryl` (string) - Cast member role.
        - `content_rating`: `NR` (enum[string]) - MPAA rating
            + Members
                + `G` - Rated G
                + `NC-17` - Rated NC-17
                + `NR` - Not rated
                + `PG` - Rated PG
                + `PG-13` - Rated PG-13
                + `R` - Rated R
                + `UR` - Unrated
                + `X` - Rated X
        - `description` (string, required) - Description, or tagline, for the movie.
        - `director`: `Lamberto Bava` (string) - Name of the director.
        - `genres` (array[string]) - Array of movie genres.
        - `imdb`: `https://www.imdb.com/title/tt0089013/` (string) - IMDB URL
        - `is_kid_friendly` (boolean) - Is this movie kid friendly?
        - `name`: `Demons` (string, required) - Name of the movie.
        - `rotten_tomatoes_score`: `56` (number) - Rotten Tomatoes score
        - `runtime`: `1hr 20min` (string) - Movie runtime, in `HHhr MMmin` format.
        - `trailer`: `https://www.youtube.com/watch?v=_cNjTdFHL8E` (string, nullable) - Trailer URL
+ Response 200 (application/json)
    + Attributes (Movie)
+ Response 400 (application/json)
    There are two ways that this status code can be encountered:
         * If there is a problem with the request.
         * If the IMDB URL could not be validated.
    + Attributes (Error)