# Group Theaters
## Movie Theaters [/theaters/{id}]
Information on a specific movie theater.

These actions will allow you to pull information on a specific movie theater.

### Get a single movie theater [GET]
+ Parameters
    - `id` (number, required) - Theater ID
+ Response 200 (application/json)
    + Attributes (Theater)
+ Response 304 (application/json)
+ Response 404 (application/json)
    + Attributes (Error)

### Update a movie theater [PATCH]
This action requires a bearer token with `create` scope.

+ Parameters
    - `id` (number, required) - Theater ID
+ Request
    + Headers

            Content-Type: application/json

    + Attributes
        - `address` (string, required) - Theater address
        - `name` (string, required) - Name of the theater.
        - `phone_number` (string, required) - Theater phone number
+ Response 200 (application/json)
    + Attributes (Theater)
+ Response 400 (application/json)
    + Attributes (Error)
+ Response 404 (application/json)
    + Attributes (Error)

### Delete a movie movie. [DELETE]
This action requires a bearer token with `delete` scope.

+ Parameters
    - `id` (number, required) - Theater ID
+ Response 204 (application/json)
+ Response 404 (application/json)
    + Attributes (Error)

## Movie Theaters [/theaters]
Information on a specific movie theater.

These actions will allow you to pull information on a specific movie theater.

### Get movie theaters. [GET]
+ Request
    + Headers

            Content-Type: application/json

    + Attributes
        - `location` (string, required) - Location you want theaters in.
+ Response 200 (application/json)
    + Attributes (array[Theater])
+ Response 400 (application/json)
    + Attributes (Error)

### Create a movie theater. [POST]
This action requires a bearer token with `create` scope.

+ Request
    + Headers

            Content-Type: application/json

    + Attributes
        - `address` (string, required) - Theater address
        - `name` (string, required) - Name of the theater.
        - `phone_number` (string, required) - Theater phone number
+ Response 200 (application/json)
    + Attributes (Theater)
+ Response 400 (application/json)
    + Attributes (Error)