## Movie
- `cast` (array[Person], required) - Cast. This data requires a bearer token with the `public` scope.
- `content_rating`: `G` (enum[string], required) - MPAA rating
    + Members
        + `G`
        + `NC-17`
        + `NR`
        + `PG`
        + `PG-13`
        + `R`
        + `UR`
        + `X`
- `description` (string, nullable) - Description
- `director` (Person, required) - Director. This data requires a bearer token with the `public` scope.
- `external_urls` (array) - External URLs. This data requires a bearer token with the `public` scope.
     - (object)
        - `imdb` (string, required) - IMDB URL. This data requires a bearer token with the `public` scope.
        - `trailer` (string, required) - Trailer URL. This data requires a bearer token with the `public` scope.
- `genres` (array[string], required) - Genres
- `id` (number, required) - Unique ID
- `kid_friendly`: `false` (boolean, required) - Kid friendly?
- `name` (string, required) - Name
- `purchase` (object)
    - `url` (string, nullable) - URL to purchase the film.
- `rotten_tomatoes_score` (number, required) - Rotten Tomatoes score
- `runtime` (string, required) - Runtime
- `showtimes` (array, required) - Non-theater specific showtimes
- `theaters` (array[Theater], required) - Theaters the movie is currently showing in
- `uri` (string, required) - Movie URI