## Person
- `id`: `1234` (number, required) - Unique ID
- `imdb`: `https://www.imdb.com/name/nm0000877/` (string, required) - IMDB URL
- `name`: `Lamberto Bava` (string, required) - Name
- `uri`: `/person/1234` (string, required) - Person URI