## Theater
- `address`: `2548 Central Park Ave, Yonkers, NY 10710` (string, required) - Address
- `id`: `1234` (number, required) - Unique ID
- `movies` (array[Movie], required) - Movies currently playing
- `name`: `Alamo Drafthouse Cinema - Yonkers` (string, required) - Name
- `phone_number`: `(914) 226-3082` (string, required) - Phone number
- `showtimes` (array[string], required) - Non-movie specific showtimes
- `uri`: `/theaters/1234` (string, required) - Theater URI