## Theater
- `address` (string) - Address
- `id` (number) - Unique ID
- `movies` (array[Movie]) - Movies currently playing
- `name` (string) - Name
- `phone_number` (string) - Phone number
- `showtimes` (array) - Non-movie specific showtimes
- `uri` (string) - Theater URI
- `website` (string) - Website