## Movie
- `cast` (array[Person], required) - Cast. This data requires a bearer token with the `public` scope.
- `content_rating`: `NR` (enum[string], required) - MPAA rating
    + Members
        + `G`
        + `NC-17`
        + `NR`
        + `PG`
        + `PG-13`
        + `R`
        + `UR`
        + `X`
- `description` (string, nullable) - Description
- `director` (Person, required) - Director. This data requires a bearer token with the `public` scope.
- `genres` (array[string], required) - Genres
- `id`: `1234` (number, required) - Unique ID
- `kid_friendly`: `false` (boolean, required) - Kid friendly?
- `name`: `Demons` (string, required) - Name
- `purchase` (object)
    - `url` (string, nullable) - URL to purchase the film.
- `rotten_tomatoes_score`: `56` (number, required) - Rotten Tomatoes score
- `runtime`: `1hr 20min` (string, required) - Runtime
- `showtimes` (array[string], required) - Non-theater specific showtimes
- `theaters` (array[Theater], required) - Theaters the movie is currently showing in
- `uri`: `/movies/1234` (string, required) - Movie URI