## Theater
- `address` (string, required) - Address
- `id` (number, required) - Unique ID
- `movies` (array[Movie], required) - Movies currently playing
- `name` (string, required) - Name
- `phone_number` (string, required) - Phone number
- `showtimes` (array[string], required) - Non-movie specific showtimes
- `uri` (string, required) - Theater URI
- `website` (string, required) - Website